language: node_js
warnings_are_errors: false

node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - CI="" npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change