language: node_js
warnings_are_errors: false

node_js:
  - "stable"
python:
  - "2.7"
cache:
  directories:
  - node_modules
install:
  - pip install --user -r api/requirements.txt
script:
  - npm test
  - pytest api
  - CI="" npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change