sudo: required
services:
  - docker

language: node_js
warnings_are_errors: false

node_js:
  - "stable"
python:
  - "2.7"
cache:
  directories:
  - node_modules
install:
  - pip install --user -r api/requirements.txt
script:
  - CI="" npm run build

after_success:
  - sh .travis/deploy_dockerhub.sh
  – test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change