sudo: required
services:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker fi

language: node_js
warnings_are_errors: false

node_js:
  - "stable"
python:
  - "2.7"
cache:
  directories:
  - node_modules
install:
  - npm install
  - pip install --user -r api/requirements.txt
script:
  - npm test
  - pytest
  - CI="" npm run build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sh .travis/deploy_dockerhub.sh fi
  – if [ "$TRAVIS_BRANCH" = "master" ]; then test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change